package com.kpi.routetracker.telegram.model.parcel;

public enum TelegramParcelCreationState {
    START,
    ASK_SENDER_PHONE,
    ASK_SENDER_NAME,
    ASK_SENDER_LAST_NAME,
    ASK_COUNTRY_SENDER,
    ASK_CITY_SENDER,
    ASK_STREET_SENDER,
    ASK_HOUSE_SENDER,
    ASK_APARTMENT_SENDER,
    ASK_RECEIVER_PHONE,
    ASK_RECEIVER_NAME,
    ASK_RECEIVER_LAST_NAME,
    ASK_COUNTRY_RECEIVER,
    ASK_CITY_RECEIVER,
    ASK_STREET_RECEIVER,
    ASK_HOUSE_RECEIVER,
    ASK_APARTMENT_RECEIVER,
    ASK_PARCEL_COUNT;
}
